# Generated by Django 4.0.2 on 2022-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_image_alter_category_id_alter_person_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='innovastion_part',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_aim',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
