# Generated by Django 3.2.13 on 2022-06-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_project_created_at_alter_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.TextField(),
        ),
    ]
